### ISSUE TITLE
triggerCharacters

### ISSUE THREAD

**Issue by lonix1** [Janne252/vscode-fontawesome-auto-complete#2]
I changed it to: `"fontAwesomeAutocomplete.triggerCharacters": ["fa"]`

But it still triggers on `f`.

**Comment by Janne252** [comment]
Hey, it appears that the trigger characters provided to [registerCompletionItemProvider ](https://code.visualstudio.com/docs/extensionAPI/vscode-api#languages.registerCompletionItemProvider) actually don't prevent the autocompletion, but rather limit the use of other completion item sources:

Here is an example where the trigger character is set to `f`: Since the word "favorite" starts with an f, Font Awesome autocomplete takes over the process and no further sources of completion items are loaded. Note the lack of "favorite" in the completion items.
![fontawesome-completion-issue-02](https://user-images.githubusercontent.com/4705573/42938671-bd96b1ce-8b5b-11e8-9101-1f903dab0815.jpg)

However when the trigger character no longer  is an f, but instead an empty array `[]`, other sources of completion items are loaded as well:
![fontawesome-completion-issue-01](https://user-images.githubusercontent.com/4705573/42938703-e15c6fae-8b5b-11e8-9747-c0943ee93560.jpg)

It also seems that providing more than one character is ignored, resulting in the same as an empty array (as above).
![fontawesome-completion-issue-03](https://user-images.githubusercontent.com/4705573/42938829-46085e0e-8b5c-11e8-9498-c92664529065.jpg)

**Answer to this specific issue:**
Based on this, triggerCharacters is a bit confusing. It is not used to prevent an unwanted completion item provider but rather to select the "master" one. I think will have to open an issue on vscode repo to confirm the logic and behavior of triggerCharacters. 

Personally I've been wondering why in some cases the list of completion items is incomplete (for example no class members in TypeScript). Apparently a matching triggerCharacters causes other sources of completion items to be ignored, as demonstrated above. This often results in polluting the list of completion items with Font Awesome names because this very extension overrides other sources of completion items if the triggerCharacters matches the current context. 

For now I think it is best not to set triggerCharacters at all. By doing that you will at least get ALL the completion items you would normally get, and not just the Font Awesome names. Unfortunately the extension default is `f`.

**Comment by lonix1** [comment]
@Janne252 Thanks. I'll upvote your vscode issue if you make one.
And thanks for this extension.

**Comment by Janne252** [comment]
@lonix1 The extension is now based on a trigger word which defaults to `fa-`. The completion item list should no longer contain all Font Awesome icons by default; Only when the trigger word is present.
